###
GET http://localhost:3000/fantasy

###
GET http://localhost:3000/fantasy/:id

###
POST http://localhost:3000/fantasy
content-type: application/json

{
    "title": "The Grimm Legacy",
    "author": "Polly Shulman",
    "published": 2011,
    "pgCount": 352,
    "synopsis": "Elizabeth is obsessed with the Brothers Grimm, and when she lands a part-time job at the New York Circulating Material Repository, a library/museum that maintains a collection of historical objects, Elizabeth discovers magical items from the Grimm fairytales in the Repository's secret basement archive.",
    "genre": "Fantasy",
    "audience": "All ages"
}

###
PUT http://localhost:3000/fantasy/:id
content-type: application/json

{
    "title": "The Grimm Legacy",
    "author": "Polly Shulman",
    "published": 2015,
    "pgCount": 352,
    "synopsis": "Elizabeth is obsessed with the Brothers Grimm, and when she lands a part-time job at the New York Circulating Material Repository, a library/museum that maintains a collection of historical objects, Elizabeth discovers magical items from the Grimm fairytales in the Repository's secret basement archive.",
    "genre": "Fantasy",
    "audience": "All ages"
}

###
DELETE http://localhost:3000/fantasy/:id